Repository commercelayer/app-orders, pull requests merged in 2023-11, with the labels that each got.

#103 Add `returns` support
  packages/app/src/App.tsx
  packages/app/src/components/FormFieldItems.tsx
  packages/app/src/components/FormReturn.tsx
  packages/app/src/components/OrderDetailsContextMenu.tsx
  packages/app/src/components/OrderReturns.tsx
  packages/app/src/data/routes.ts
  packages/app/src/hooks/useCreateReturnLineItems.tsx
  packages/app/src/hooks/useOrderDetails.tsx
  packages/app/src/hooks/useReturn.tsx
  packages/app/src/hooks/useReturnableList.tsx
  packages/app/src/pages/CreateReturn.tsx
  packages/app/src/pages/OrderDetails.tsx
Labels: enhancement

#107 Update deps add `Metadata` management in order detail
  packages/app/package.json
  packages/app/src/components/OrderReturns.tsx
  packages/app/src/hooks/useOrderReturns.tsx
  packages/app/src/pages/OrderDetails.tsx
  pnpm-lock.yaml
Labels: enhancement

#108 v1.3.1
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#109 Show `returns stock_location` in `returns list`
  packages/app/package.json
  packages/app/src/hooks/useOrderReturns.tsx
  pnpm-lock.yaml
Labels: bug

#110 v1.3.2
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#101 Enable internal preview link
  .circleci/config.yml
  .github/workflows/preview-link.yaml
Labels: enhancement, ignore-for-release

#111 Add GTM support
  packages/app/global.d.ts
  packages/app/src/App.tsx
Labels: enhancement

#112 Update `ResourceAddress` from app-elements
  packages/app/package.json
  packages/app/src/components/OrderAddresses.tsx
  packages/app/src/pages/CreateReturn.tsx
  pnpm-lock.yaml
Labels: enhancement

#113 v1.3.3
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#115 Update app-elements + sdk
  packages/app/package.json
  pnpm-lock.yaml
Labels: enhancement

#116 v1.3.4
  lerna.json
  packages/app/package.json
Labels: ignore-for-release
