Repository commercelayer/app-orders, pull requests merged in 2024-06, with the labels that each got.

#171 Update dependencies
  package.json
  packages/app/package.json
  packages/app/src/metricsApi/useListCounters.ts
  pnpm-lock.yaml
Labels: enhancement

#172 v1.8.1
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#173 Export 'Main' component as default
  packages/app/src/main.tsx
Labels: enhancement, ignore-for-release

#174 Update all packages to latest major
  package.json
  packages/app/package.json
  packages/app/src/hooks/useOrderToolbar.tsx
  packages/app/src/pages/OrderDetails.tsx
  packages/app/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#175 v1.8.2
  lerna.json
  packages/app/package.json
Labels: ignore-for-release
