Repository commercelayer/app-orders, pull requests merged in 2024-01, with the labels that each got.

#118 Add line item options
  packages/app/src/hooks/useOrderDetails.tsx
Labels: enhancement

#120 Update packages to latest minor version to bump `app-elements` components
  packages/app/package.json
  packages/app/src/components/OrderCustomer.tsx
  packages/app/src/components/OrderPayment.tsx
  packages/app/src/components/OrderShipments.tsx
  packages/app/src/components/OrderSummary/ListItemSkuBundle.tsx
  packages/app/src/components/OrderSummary/hooks/useAddCouponOverlay.tsx
  packages/app/src/components/OrderSummary/hooks/useAddItemOverlay.tsx
  packages/app/src/components/OrderSummary/hooks/useAdjustTotalOverlay.tsx
  packages/app/src/components/OrderSummary/hooks/useSelectShippingMethodOverlay.tsx
  packages/app/src/components/RefundForm.tsx
  packages/app/src/components/ScrollToTop.tsx
  packages/app/src/hooks/useCancelOverlay.tsx
  packages/app/src/hooks/useCaptureOverlay.tsx
  packages/app/src/hooks/useOrderDetails.tsx
  packages/app/src/hooks/useReturnableList.tsx
  packages/app/src/main.tsx
  packages/app/src/pages/CreateReturn.tsx
  packages/app/src/pages/Filters.tsx
  packages/app/src/pages/Home.tsx
  packages/app/src/pages/OrderDetails.tsx
  packages/app/src/pages/OrderList.tsx
  packages/app/src/utils/getOrderTitle.ts
  packages/app/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#123 v1.3.6
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#124 Fix Order detail back button behavior
  .vscode/settings.json
  packages/app/src/pages/Home.tsx
  packages/app/src/pages/OrderDetails.tsx
Labels: bug

#117 Toggle on the order editing feature
  packages/app/src/components/OrderSummary/HeaderActions.tsx
Labels: enhancement

#125 v1.4.0
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#126 Update `app-elements` to apply recent `Timeline` fixes
  .circleci/config.yml
  packages/app/package.json
  packages/app/public/config.preview-prd.js
  packages/app/public/config.preview-stg.js
  packages/app/src/pages/Home.tsx
  pnpm-lock.yaml
Labels: bug

#127 v1.4.1
  lerna.json
  packages/app/package.json
Labels: ignore-for-release
