Repository commercelayer/app-orders, pull requests merged in 2024-05, with the labels that each got.

#163 Update dependencies
  package.json
  packages/app/package.json
  packages/app/src/main.tsx
  pnpm-lock.yaml
Labels: enhancement

#164 v1.7.8
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#165 Fix tag click action in order detail
  packages/app/src/pages/OrderDetails.tsx
Labels: bug

#166 v1.7.9
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#167 Update app-elements package to latest version
  packages/app/package.json
  pnpm-lock.yaml
Labels: enhancement

#168 v1.7.10
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#169 Update app-elements to 2.x
  packages/app/package.json
  packages/app/src/hooks/useOrderToolbar.tsx
  packages/app/src/mocks/index.ts
  packages/app/src/mocks/resource.ts
  packages/app/src/pages/OrderDetails.tsx
  packages/app/src/pages/OrderList.tsx
  pnpm-lock.yaml
Labels: enhancement

#170 v1.8.0
  lerna.json
  packages/app/package.json
Labels: ignore-for-release
