Repository commercelayer/app-orders, pull requests merged in 2024-04, with the labels that each got.

#150 Update dependencies
  package.json
  packages/app/package.json
  packages/app/src/components/FormFieldItems.tsx
  packages/app/src/components/ListItemOrder.tsx
  packages/app/src/components/OrderCustomer.tsx
  packages/app/src/components/OrderPayment.tsx
  packages/app/src/components/OrderShipments.tsx
  packages/app/src/components/OrderSummary/ListItemSkuBundle.tsx
  packages/app/src/components/OrderSummary/hooks/useSelectShippingMethodOverlay.tsx
  packages/app/src/components/OrderSummary/utils.tsx
  packages/app/src/pages/Home.tsx
  pnpm-lock.yaml
Labels: enhancement

#152 v1.7.2
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#153 Update elements and set metadata mode simple
  packages/app/package.json
  packages/app/src/pages/OrderDetails.tsx
  pnpm-lock.yaml
Labels: bug

#154 v1.7.3
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#155 Update CDN Link
  packages/app/index.html
Labels: bug, enhancement

#157 Enable search for pending orders
  packages/app/src/pages/OrderList.tsx
Labels: enhancement

#158 v1.7.5
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#159 Update app-elements
  packages/app/package.json
  pnpm-lock.yaml
Labels: enhancement

#160 v1.7.6
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#161 Update UI
  packages/app/package.json
  packages/app/src/components/OrderDetailsContextMenu.tsx
  packages/app/src/components/OrderSummary/HeaderActions.tsx
  packages/app/src/components/RefundForm.tsx
  packages/app/src/main.tsx
  packages/app/src/pages/OrderList.tsx
  pnpm-lock.yaml
Labels: enhancement

#162 v1.7.7
  lerna.json
  packages/app/package.json
Labels: ignore-for-release
