Repository commercelayer/app-orders, pull requests merged in 2024-07, with the labels that each got.

#177 Hide archived orders from open lists
  packages/app/src/data/lists.ts
Labels: enhancement

#178 v1.8.3
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#180 Use same listing page logic to build filter query for counters
  packages/app/src/metricsApi/useListCounters.ts
Labels: bug

#181 v1.8.4
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#183 Update action button labels + show the shipping and payment method names
  packages/app/src/components/OrderSummary/SummaryRows.tsx
  packages/app/src/components/OrderSummary/hooks/useActionButtons.tsx
  packages/app/src/components/OrderSummary/orderDictionary.ts
Labels: enhancement

#182 Sort order list by `placed_at`
  packages/app/src/pages/OrderList.tsx
Labels: bug

#185 Update elements to latest
  packages/app/package.json
  pnpm-lock.yaml
Labels: enhancement

#186 Rollback shipping method name change
  packages/app/src/components/OrderSummary/SummaryRows.tsx
Labels: bug
